SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
       ROUND((SELECT AVG(REVIEW_SCORE)
              FROM REST_REVIEW RR
              WHERE RR.REST_ID = RI.REST_ID), 2) as SCORE
FROM REST_INFO RI
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
HAVING SCORE IS NOT NULL
ORDER BY SCORE DESC , FAVORITES DESC